package azenzus.resources;

public class Links {
    public static String[][] searchLinks = {{"//div[contains(@eventproxy,'searchMenu')]//div[text() = 'Equipment']",
            "//table[@height = '18px']//td[text() = 'Equipment Manager']",
            "//div[contains(@eventproxy,'QueryManagerWindowNew_0_max')]",
            "//div[contains(@eventproxy,'QueryManagerWindowNew_0_min')]",
            "//div[contains(@eventproxy,'QueryManagerWindowNew_0_cl')]",
            "//div[contains(@eventproxy,'QueryManagerWindowNew_0')]//input[@name = 'searchTextBox']",
            "//div[contains(@eventproxy,'QueryManagerWindowNew_0')]//div[text() = 'Start Editing']",
            "//div[contains(@eventproxy,'QueryManagerWindowNew_0')]//div[text() = 'Conditions reset']",
            "//div[contains(@eventproxy,'QueryManagerWindowNew_0')]//div[text() = 'Layout reset']",
            "//div[contains(@eventproxy,'QueryManagerWindowNew_0')]//div[text() = 'Report...']",
            "//div[contains(@eventproxy,'QueryManagerWindowNew_0')]//div[text() = 'Search']",
    },{     "//div[contains(@eventproxy,'searchMenu')]//div[text() = 'Contact']",
            "//table[@height='18px']//td[text()='Contact Manager']",
            "//div[contains(@eventproxy,'ContactManagerWindow_0_max')]",
            "//div[contains(@eventproxy,'ContactManagerWindow_0_min')]",
            "//div[contains(@eventproxy,'ContactManagerWindow_0_cl')]",
            "//div[contains(@eventproxy,'ContactManagerWindow_0')]//input[@name = 'CMSearchText']",
            null,
            null,
            null,
            null,
            "//div[contains(@eventproxy,'CMDynamic')]//div[text()='Search']",
    },{
            "//div[contains(@eventproxy,'searchMenu')]//div[text() = 'Document']",
            "//table[@height = '18px']//td[text() = 'Document Manager']",
            "//div[contains(@eventproxy,'DocumentManagerSearchWindowNew_0_max')]",
            "//div[contains(@eventproxy,'DocumentManagerSearchWindowNew_0_min')]",
            "//div[contains(@eventproxy,'DocumentManagerSearchWindowNew_0_cl')]",
            "//div[contains(@eventproxy,'DocumentManagerSearchWindowNew_0')]//input[@name = 'searchTextBox']",
            "//div[contains(@eventproxy,'DocumentManagerSearchWindowNew_0')]//div[text() = 'Start Editing']",
            "//div[contains(@eventproxy,'DocumentManagerSearchWindowNew_0')]//div[text() = 'Conditions reset']",
            "//div[contains(@eventproxy,'DocumentManagerSearchWindowNew_0')]//div[text() = 'Layout reset']",
            "//div[contains(@eventproxy,'DocumentManagerSearchWindowNew_0')]//div[text() = 'Report...']",
            "//div[contains(@eventproxy,'DocumentManagerSearchWindowNew_0')]//div[text() = 'Search']",
    },{
            "//div[contains(@eventproxy,'searchMenu')]//div[text() = 'Aspect']",
            "//table[@height = '18px']//td[text() = 'Aspect Manager']",
            "//div[contains(@eventproxy,'RecordSearchWindow_0_max')]",
            "//div[contains(@eventproxy,'RecordSearchWindow_0_min')]",
            "//div[contains(@eventproxy,'RecordSearchWindow_0_cl')]",
            "//div[contains(@eventproxy,'RecordSearchWindow_0')]//input[@name = 'searchTextBox']",
            "//div[contains(@eventproxy,'RecordSearchWindow_0')]//div[text() = 'Start Editing']",
            "//div[contains(@eventproxy,'RecordSearchWindow_0')]//div[text() = 'Conditions reset']",
            "//div[contains(@eventproxy,'RecordSearchWindow_0')]//div[text() = 'Layout reset']",
            "//div[contains(@eventproxy,'RecordSearchWindow_0')]//div[text() = 'Report...']",
            "//div[contains(@eventproxy,'RecordSearchWindow_0')]//div[text() = 'Search']",
    },{
            "//div[contains(@eventproxy,'searchMenu')]//div[text() = 'Comment']",
            "//table[@height = '18px']//td[text() = 'Comments']",
            "//div[contains(@eventproxy,'CommentSearchWindowNew_0_max')]",
            "//div[contains(@eventproxy,'CommentSearchWindowNew_0_min')]",
            "//div[contains(@eventproxy,'CommentSearchWindowNew_0_cl')]",
            "//div[contains(@eventproxy,'CommentSearchWindowNew_0')]//input[@name = 'searchText']",
            null,
            null,
            "//div[contains(@eventproxy,'CommentSearchWindowNew_0')]//div[text() = 'Reset']",
            "//div[contains(@eventproxy,'CommentSearchWindowNew_0')]//div[text() = 'Report']",
            "//div[contains(@eventproxy,'CommentSearchWindowNew_0')]//div[text() = 'Search']",
       }
    };
    public static String[][] toolLinks = {{
            "//div[text() = 'Trashed Items Manager']",
            null,
            "//table[@height = '18px']//td[text() = 'Trashed Items Manager']",
            "//div[contains(@eventproxy,'TrashedItemsManagerWindow_0_max')]",
            "//div[contains(@eventproxy,'TrashedItemsManagerWindow_0_min')]",
            "//div[contains(@eventproxy,'TrashedItemsManagerWindow_0_cl')]",
            "//div[contains(@eventproxy,'TrashedItemsManagerWindow_0')]//input[@name = 'searchTextBox']",
            "//div[contains(@eventproxy,'TrashedItemsManagerWindow_0')]//div[text() = 'Conditions reset']",
            "//div[contains(@eventproxy,'TrashedItemsManagerWindow_0')]//div[text() = 'Layout reset']",
            "//div[contains(@eventproxy,'TrashedItemsManagerWindow_0')]//div[text() = 'Search']",
    },{
            "//div[text() = 'Queue Manager']",
            null,
            "//table[@height = '18px']//td[text() = 'Queue manager']",
            "//div[contains(@eventproxy,'QueueManagerWindow_0_max')]",
            "//div[contains(@eventproxy,'QueueManagerWindow_0_min')]",
            "//div[contains(@eventproxy,'QueueManagerWindow_0_cl')]",
            "//div[contains(@eventproxy,'QueueManagerWindow_0')]//table[contains(@style,'772') ]",
            null,
            null,
            "//div[contains(@eventproxy,'QueueManagerWindow_0')]//table[contains(@style,'772') ]",
            "//div[contains(@eventproxy,'ListMenu')]//div[text() = 'EXPORT']",
    },{
            "//div[text() = 'Import Meta']",
            null,
            "//table[@height = '18px']//td[text() = 'Import Meta Manager']",
            "//div[contains(@eventproxy,'ImportMetaWindow_0_max')]",
            "//div[contains(@eventproxy,'ImportMetaWindow_0_min')]",
            "//div[contains(@eventproxy,'ImportMetaWindow_0_cl')]",
            null,
            "//div[contains(@eventproxy,'ImportMetaWindow_0')]//div[text() = 'Add file']",
            "//div[contains(@eventproxy,'ImportMetaWindow_0')]//div[text() = 'Import']",
    },{
            "//div[text() = 'Import (dynamic)']",
            null,
            "//table[@height = '18px']//td[text() = 'Import Manager']",
            "//div[contains(@eventproxy,'SyncManagerWindow_0_max')]",
            "//div[contains(@eventproxy,'SyncManagerWindow_0_min')]",
            "//div[contains(@eventproxy,'SyncManagerWindow_0_cl')]",
            null,
            "//div[contains(@eventproxy,'SyncManagerWindow_0')]//div[text() = 'Prepare']",
            "//div[contains(@eventproxy,'SyncManagerWindow_0')]//div[text() = 'Import']",
    },{
            "//div[text() = 'Administration']",
            "//div[@role = 'menu']//div[text() = 'Plant']",

            "//table[@height = '18px']//td[text() = 'Plant Search']",
            "//div[contains(@eventproxy,'PlantManagerSearchWindow_0_max')]",
            "//div[contains(@eventproxy,'PlantManagerSearchWindow_0_min')]",
            "//div[contains(@eventproxy,'PlantManagerSearchWindow_0_cl')]",
            "//div[contains(@eventproxy,'PlantManagerSearchWindow_0')]//input",
            "//div[contains(@eventproxy,'PlantManagerSearchWindow_0')]//div[text() ='Search']",
            null,
            "//div[contains(@eventproxy,'PlantManagerSearchWindow_0')]//div[text() ='Search']",
    },{
            "//div[text() = 'Administration']",
            "//div[@role = 'menu']//div[text() = 'User Profile']",

            "//table[@height = '18px']//td[text() = 'User Profile']",
            null,
            null,
            "//div[contains(@eventproxy,'UserProfileWindow_0_cl')]",
            "//div[contains(@eventproxy,'UserProfileWindow_0')]//input[@name = 'password']",
            "//div[contains(@eventproxy,'UserProfileWindow_0')]//div[text() = 'Save']",
            null,
    }};
    public static String[][] dataManagerLinks = {{
            "//div[text() = 'Link Types Manager']",
            null,
            null,
            "//table[@height = '18px']//td[text() = 'Link Types Manager']",

            "//div[contains(@eventproxy,'LinkTypesManager_0_max')]",
            "//div[contains(@eventproxy,'LinkTypesManager_0_min')]",
            "//div[contains(@eventproxy,'LinkTypesManager_0_cl')]",
            null,
            "//div[contains(@eventproxy,'LinkTypesManager_0')]//div[text() = 'Add']",
            "//div[contains(@eventproxy,'LinkTypesManager_0')]//div[text() = 'Edit']",
            "//div[contains(@eventproxy,'LinkTypesManager_0')]//div[text() = 'Remove']",
    },{
            "//div[text() = 'Reports Manager']",
            null,
            null,
            "//table[@height = '18px']//td[text() = 'Report Manager']",

            "//div[contains(@eventproxy,'ReportManagerWindow_0_max')]",
            "//div[contains(@eventproxy,'ReportManagerWindow_0_min')]",
            "//div[contains(@eventproxy,'ReportManagerWindow_0_cl')]",
            "//div[contains(@eventproxy,'ReportManagerWindow_0')]//div[contains(@style , 'width:746')]",
            "//div[contains(@eventproxy,'ReportManagerWindow_0')]//div[text() = 'Generate']",
            null,
            null,
    },{
            "//div[text() = 'Unit Manager']",
            null,
            null,
            "//table[@height = '18px']//td[text() = 'Unit Manager']",
            "//div[contains(@eventproxy,'UnitManagerWindow_0_max')]",
            "//div[contains(@eventproxy,'UnitManagerWindow_0_min')]",
            "//div[contains(@eventproxy,'UnitManagerWindow_0_cl')]",
            "//div[contains(@eventproxy,'UnitManagerWindow_0')]//input[@name = 'searchText']",
            "//div[contains(@eventproxy,'UnitManagerWindow_0')]//div[text() = 'Search']",
            null,
            null,
            "//div[contains(@eventproxy,'UnitManagerWindow_0')]//div[text() = 'Search']",
    },{
            "//div[text() = 'Role Manager']",
            null,
            null,
            "//table[@height = '18px']//td[text() = 'Role Manager']",
            "//div[contains(@eventproxy,'RoleManagerWindow_0_max')]",
            "//div[contains(@eventproxy,'RoleManagerWindow_0_min')]",
            "//div[contains(@eventproxy,'RoleManagerWindow_0_cl')]",
            null,
            "//div[contains(@eventproxy,'RoleManagerWindow_0')]//div[text() = 'Add Role']",
            "//div[contains(@eventproxy,'RoleManagerWindow_0')]//div[text() = 'Start Editing']",
            "//div[contains(@eventproxy,'RoleManagerWindow_0')]//div[text() = 'Remove Role']",
    },{
            "//div[text() = 'Masterdata']",
            "//div[contains(@eventproxy,'isc_Menu')]//div[text() ='Equipment']",
            null,
            "//table[@height = '18px']//td[text() = 'Masterdata -> Equipment']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_0_max')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_0_min')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_0_cl')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_0')]//input[@name = 'searchText']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_0')]//div[text() = 'Reset']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_0')]//div[text() = 'Report']",
            null,
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_0')]//div[text() = 'Search']",
    },{
            "//div[text() = 'Masterdata']",
            "//div[contains(@eventproxy,'isc_Menu')]//div[text() ='Spare Parts']",
            null,
            "//table[@height = '18px']//td[text() = 'Masterdata -> Spare Parts']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_1_max')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_1_min')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_1_cl')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_1')]//input[@name = 'searchText']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_1')]//div[text() = 'Reset']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_1')]//div[text() = 'Report']",
            null,
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_1')]//div[text() = 'Search']",
    },{
            "//div[text() = 'Masterdata']",
            "//div[contains(@eventproxy,'isc_Menu')]//div[text() ='Document']",
            null,
            "//table[@height = '18px']//td[text() = 'Masterdata -> Documents']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_2_max')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_2_min')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_2_cl')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_2')]//input[@name = 'searchText']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_2')]//div[text() = 'Reset']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_2')]//div[text() = 'Report']",
            null,
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_2')]//div[text() = 'Search']",
    },{
            "//div[text() = 'Masterdata']",
            "//div[contains(@eventproxy,'isc_Menu')]//div[text() ='Other...']",
            null,
            "//table[@height = '18px']//td[text() = 'Masterdata -> Other...']",
            "//div[contains(@eventproxy,'MasterdataManagerWindow_0_max')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindow_0_min')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindow_0_cl')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindow_0')]//input[@name = 'searchText']",
            "//div[contains(@eventproxy,'MasterdataManagerWindow_0')]//div[text() = 'Reset']",
            "//div[contains(@eventproxy,'MasterdataManagerWindow_0')]//div[text() = 'Report']",
            null,
            "//div[contains(@eventproxy,'MasterdataManagerWindow_0')]//div[text() = 'Search']",
    },{
            "//div[text() = 'N&M Manager']",
            "//div[contains(@style,'150px')]//div[text() = 'Product']",
            null,
            "//table[@height = '18px']//td[contains(text(),'PRODUCT')]",
            null,
            "//div[contains(@eventproxy,'KBWindow_0_min')]",
            "//div[contains(@eventproxy,'KBWindow_0_cl')]",
            null,
            "//div[contains(@eventproxy,'KBWindow_0')]//div[contains(@style , 'left: 220px')]",
            "//div[contains(@eventproxy,'KBWindow_0')]//div[contains(@style , 'left: 225px')]", //add button
            null,
    },{
            "//div[text() = 'N&M Manager']",
            "//div[contains(@style,'150px')]//div[text() = 'Location']",
            null,
            "//table[@height = '18px']//td[contains(text(),'LOCATION')]",
            null,
            "//div[contains(@eventproxy,'KBWindow_1_min')]",
            "//div[contains(@eventproxy,'KBWindow_1_cl')]",
            null,
            "//div[contains(@eventproxy,'KBWindow_1')]//div[contains(@style , 'left: 220px')]",
            "//div[contains(@eventproxy,'KBWindow_1')]//div[contains(@style , 'left: 225px')]", //add button
            null
    },{
            "//div[text() = 'N&M Manager']",
            "//div[contains(@style,'150px')]//div[text() = 'Document']",
            null,
            "//table[@height = '18px']//td[contains(text(),'DOCUMENT')]",
            null,
            "//div[contains(@eventproxy,'KBWindow_2_min')]",
            "//div[contains(@eventproxy,'KBWindow_2_cl')]",
            null,
            "//div[contains(@eventproxy,'KBWindow_2')]//div[contains(@style , 'left: 220px')]",
            "//div[contains(@eventproxy,'KBWindow_2')]//div[contains(@style , 'left: 225px')]", //add button
            null
    },{
            "//div[text() = 'N&M Manager']",
            "//div[contains(@style,'150px')]//div[text() = 'Other']",
            null,
            "//table[@height = '18px']//td[contains(text(),'OTHER')]",
            null,
            "//div[contains(@eventproxy,'KBWindow_3_min')]",
            "//div[contains(@eventproxy,'KBWindow_3_cl')]",
            null,
            "//div[contains(@eventproxy,'KBWindow_3')]//div[contains(@style , 'left: 220px')]",
            "//div[contains(@eventproxy,'KBWindow_3')]//div[contains(@style , 'left: 225px')]", //add button
            null
    },{
            "//div[text() = 'N&M Manager']",
            "//div[contains(@style,'150px')]//div[text() = 'Characteristic']",
            null,
            "//table[@height = '18px']//td[contains(text(),'CHARACTERISTIC')]",
            null,
            "//div[contains(@eventproxy,'KBWindow_4_min')]",
            "//div[contains(@eventproxy,'KBWindow_4_cl')]",
            null,
            "//div[contains(@eventproxy,'KBWindow_4')]//div[contains(@style , 'left: 220px')]",
            "//div[contains(@eventproxy,'KBWindow_4')]//div[contains(@style , 'left: 225px')]", //add button
            null
    },{
            "//div[text() = 'N&M Manager']",
            "//div[contains(@style,'150px')]//div[text() = 'Function']",
            null,
            "//table[@height = '18px']//td[contains(text(),'FUNCTION')]",
            null,
            "//div[contains(@eventproxy,'KBWindow_5_min')]",
            "//div[contains(@eventproxy,'KBWindow_5_cl')]",
            null,
            "//div[contains(@eventproxy,'KBWindow_5')]//div[contains(@style , 'left: 220px')]",
            "//div[contains(@eventproxy,'KBWindow_5')]//div[contains(@style , 'left: 225px')]", //add button
            null
    },{
            "//div[text() = 'Synchronize']",
            "//div[text()='Master']",
            null,
            "//table[@height = '18px']//td[text() = 'Master Product Synchronization']",
            "//div[contains(@eventproxy,'KBWindow_6_max')]",
            "//div[contains(@eventproxy,'KBWindow_6_min')]",
            "//div[contains(@eventproxy,'KBWindow_6_cl')]",
            "//div[contains(@eventproxy,'KBWindow_6')]//input[@name = 'searchText']",
            "//div[contains(@eventproxy,'KBWindow_6')]//div[text() = 'Reset']",
            "//div[contains(@eventproxy,'KBWindow_6')]//div[text() = 'Report']",
            "//div[contains(@eventproxy,'KBWindow_6')]//div[text() = 'Synchronize']",
            "//div[contains(@eventproxy,'KBWindow_6')]//div[text() = 'Search']",
    },{
            "//div[text() = 'Synchronize']",
            "//div[contains(@style , 'top: 42')]//div[text()='Spare Parts']",
            null,
            "//table[@height = '18px']//td[text() = 'Spare Parts Synchronization']",
            "//div[contains(@eventproxy,'KBWindow_7_max')]",
            "//div[contains(@eventproxy,'KBWindow_7_min')]",
            "//div[contains(@eventproxy,'KBWindow_7_cl')]",
            "//div[contains(@eventproxy,'KBWindow_7')]//input[@name = 'searchText']",
            "//div[contains(@eventproxy,'KBWindow_7')]//div[text() = 'Reset']",
            "//div[contains(@eventproxy,'KBWindow_7')]//div[text() = 'Report']",
            "//div[contains(@eventproxy,'KBWindow_7')]//div[text() = 'Synchronize']",
            "//div[contains(@eventproxy,'KBWindow_7')]//div[text() = 'Search']",
    },{
            "//div[text() = 'Synchronize']",
            "//div[text()='Instance']",
            "//div[contains(@style , 'top: 52')]//div[text()='Equipment']",
            "//table[@height = '18px']//td[text() = 'Equipment Synchronization']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_0_max')]",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_0_min')]",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_0_cl')]",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_0')]//input[@name = 'searchTextBox']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_0')]//div[text() = 'Conditions reset']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_0')]//div[text() = 'Report...']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_0')]//div[text() = 'Synchronize']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_0')]//div[text() = 'Search']",
    },{
            "//div[text() = 'Synchronize']",
            "//div[text()='Instance']",
            "//div[contains(@style , 'top: 52')]//div[text()='Documents']",
            "//table[@height = '18px']//td[text() = 'Document Instance Synchronization']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_1_max')]",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_1_min')]",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_1_cl')]",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_1')]//input[@name = 'searchTextBox']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_1')]//div[text() = 'Conditions reset']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_1')]//div[text() = 'Report...']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_1')]//div[text() = 'Synchronize']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_1')]//div[text() = 'Search']",
    },{
            "//div[text() = 'Synchronize']",
            "//div[text()='Instance']",
            "//div[contains(@style , 'top: 52')]//div[text()='Aspect']",
            "//table[@height = '18px']//td[text() = 'Aspect Synchronization']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_2_max')]",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_2_min')]",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_2_cl')]",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_2')]//input[@name = 'searchTextBox']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_2')]//div[text() = 'Conditions reset']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_2')]//div[text() = 'Report...']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_2')]//div[text() = 'Synchronize']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_2')]//div[text() = 'Search']",
    }};
    public static String contextMenuLocation[] = {"//div[@eventproxy = 'isc_Menu_100']//div[text() = 'Synchronize...']",
            "//div[@eventproxy = 'isc_Menu_100']//div[text() = 'Edit...']",
            "//div[@eventproxy = 'isc_Menu_100']//div[text() = 'Edit Dummy Master...']",
            "//div[@eventproxy = 'isc_Menu_100']//div[contains(text() , 'Noun')]",
            "//div[@eventproxy = 'isc_Menu_100']//div[text() = 'Bulk Add Contact...']",
            "//div[@eventproxy = 'isc_Menu_100']//div[text() = 'Mapping links']",
            "//div[@eventproxy = 'isc_Menu_100']//div[text() = 'Model Tree']",
            "//div[@eventproxy = 'isc_Menu_100']//div[text() = 'Detach']",
            "//div[@eventproxy = 'isc_Menu_100']//div[contains(text() , ' to trash')]",
            "//div[@eventproxy = 'isc_Menu_100']//div[text() = 'Replace Metadata...']",
            "//div[@eventproxy = 'isc_Menu_100']//div[text() = 'Visibility...']",
            "//div[@eventproxy = 'isc_Menu_100']//div[text() = 'History...']",
            "//div[@eventproxy = 'isc_Menu_100']//div[text() = 'Details...']",
            "//div[@eventproxy = 'isc_Menu_100']//div[text() = 'Locator...']",
            "//div[@eventproxy = 'isc_Menu_100']//div[contains(text() , 'Order ')]",
            "//div[@eventproxy = 'isc_Menu_100']//div[contains(text() , 'Change ')]",
            "//div[@eventproxy = 'isc_Menu_100']//div[text() = 'Print']",
            "//div[@eventproxy = 'isc_Menu_100']//div[text() = 'Refresh']",
            "//div[@eventproxy = 'isc_Menu_100']//div[text() = 'Expand All']",
            "//div[@eventproxy = 'isc_Menu_100']//div[text() = 'Collapse All']"
    };
    public static String contextMenuFunction[] = {"//div[@eventproxy = 'isc_Menu_16']//div[text() = 'Synchronize...']",
            "//div[@eventproxy = 'isc_Menu_16']//div[text() = 'Edit...']",
            "//div[@eventproxy = 'isc_Menu_16']//div[text() = 'Edit Dummy Master...']",
            "//div[@eventproxy = 'isc_Menu_16']//div[contains(text() , 'Noun')]",
            "//div[@eventproxy = 'isc_Menu_16']//div[text() = 'Bulk Add Contact...']",
            "//div[@eventproxy = 'isc_Menu_16']//div[text() = 'Mapping links']",
            "//div[@eventproxy = 'isc_Menu_16']//div[text() = 'Model Tree']",
            "//div[@eventproxy = 'isc_Menu_16']//div[text() = 'Detach']",
            "//div[@eventproxy = 'isc_Menu_16']//div[contains(text() , ' to trash')]",
            "//div[@eventproxy = 'isc_Menu_16']//div[text() = 'Replace Metadata...']",
            "//div[@eventproxy = 'isc_Menu_16']//div[text() = 'Visibility...']",
            "//div[@eventproxy = 'isc_Menu_16']//div[text() = 'History...']",
            "//div[@eventproxy = 'isc_Menu_16']//div[text() = 'Details...']",
            "//div[@eventproxy = 'isc_Menu_16']//div[text() = 'Locator...']",
            "//div[@eventproxy = 'isc_Menu_16']//div[contains(text() , 'Order ')]",
            "//div[@eventproxy = 'isc_Menu_16']//div[contains(text() , 'Change ')]",
            "//div[@eventproxy = 'isc_Menu_16']//div[text() = 'Print']",
            "//div[@eventproxy = 'isc_Menu_16']//div[text() = 'Refresh']",
            "//div[@eventproxy = 'isc_Menu_16']//div[text() = 'Expand All']",
            "//div[@eventproxy = 'isc_Menu_16']//div[text() = 'Collapse All']"
    };
    public static String contextMenuDocument[] = {"//div[@eventproxy = 'isc_Menu_33']//div[text() = 'Synchronize...']",
            "//div[@eventproxy = 'isc_Menu_33']//div[text() = 'Edit...']",
            "//div[@eventproxy = 'isc_Menu_33']//div[text() = 'Edit Dummy Master...']",
            "//div[@eventproxy = 'isc_Menu_33']//div[contains(text() , 'Noun')]",
            "//div[@eventproxy = 'isc_Menu_33']//div[text() = 'Bulk Add Contact...']",
            "//div[@eventproxy = 'isc_Menu_33']//div[text() = 'Mapping links']",
            "//div[@eventproxy = 'isc_Menu_33']//div[text() = 'Model Tree']",
            "//div[@eventproxy = 'isc_Menu_33']//div[text() = 'Detach']",
            "//div[@eventproxy = 'isc_Menu_33']//div[contains(text() , ' to trash')]",
            "//div[@eventproxy = 'isc_Menu_33']//div[text() = 'Replace Metadata...']",
            "//div[@eventproxy = 'isc_Menu_33']//div[text() = 'Visibility...']",
            "//div[@eventproxy = 'isc_Menu_33']//div[text() = 'History...']",
            "//div[@eventproxy = 'isc_Menu_33']//div[text() = 'Details...']",
            "//div[@eventproxy = 'isc_Menu_33']//div[text() = 'Locator...']",
            "//div[@eventproxy = 'isc_Menu_33']//div[contains(text() , 'Order ')]",
            "//div[@eventproxy = 'isc_Menu_33']//div[contains(text() , 'Change ')]",
            "//div[@eventproxy = 'isc_Menu_33']//div[text() = 'Print']",
            "//div[@eventproxy = 'isc_Menu_33']//div[text() = 'Refresh']",
            "//div[@eventproxy = 'isc_Menu_33']//div[text() = 'Expand All']",
            "//div[@eventproxy = 'isc_Menu_33']//div[text() = 'Collapse All']",
    };
    public static String subContextMenuLoc[] = {
            "//div[@eventproxy = 'isc_Menu_110']//div[contains(text() , 'Product')]",
            "//div[@eventproxy = 'isc_Menu_110']//table[@width = 146]//div[contains(text() , 'Function')]",
            "//div[@eventproxy = 'isc_Menu_110']//table[@width = 146]//div[contains(text() , 'Location')]",
            "//div[@eventproxy = 'isc_Menu_110']//table[@width = 146]//div[text() = 'Document']",
            "//div[@eventproxy = 'isc_Menu_110']//div[contains(text() , 'Characteristic')]",
            "//div[@eventproxy = 'isc_Menu_110']//div[contains(text() , 'Other')]",
            "//div[@eventproxy = 'isc_Menu_111']//div[contains(text() , 'Add root node...')]",
            "//div[@eventproxy = 'isc_Menu_111']//div[contains(text() , 'Add sub node...')]",
            "//div[@eventproxy = 'isc_Menu_111']//div[contains(text() , 'Edit RDCs...')]",
            "//div[@eventproxy = 'isc_Menu_111']//div[contains(text() , 'Rename RDC...')]",
            "//div[@eventproxy = 'isc_Menu_111']//div[contains(text() , 'Delete node')]",
            "//div[@eventproxy = 'isc_Menu_111']//div[contains(text() , 'Delete aspect with')]",
            "//div[@eventproxy = 'isc_Menu_112']//table[@width = 146]//div[text() = 'Detach']",
            "//div[@eventproxy = 'isc_Menu_112']//div[contains(text() , 'in this Tree')]",
            "//div[@eventproxy = 'isc_Menu_112']//div[contains(text() , 'in all Trees')]",
            "//div[@eventproxy = 'isc_Menu_113']//div[contains(text() , 'Catalogue')]",
            "//div[@eventproxy = 'isc_Menu_113']//div[contains(text() , 'Constrained')]",
            "//div[@eventproxy = 'isc_Menu_113']//div[contains(text() , 'Abstract')]",
            "//div[@eventproxy = 'isc_Menu_120']//div[contains(@style ,'125px')]//div[text() = 'Catalogue']",
            "//div[@eventproxy = 'isc_Menu_120']//div[contains(@style ,'125px')]//div[text() = 'Catalogue > Constrained...']",
            "//div[@eventproxy = 'isc_Menu_120']//div[contains(@style ,'125px')]//div[text() = 'Abstract > Constrained...']",
            "//div[@eventproxy = 'isc_Menu_120']//div[contains(@style ,'125px')]//div[text() = 'Constrained > Abstract...']",
            "//div[@eventproxy = 'isc_Menu_120']//div[contains(@style ,'125px')]//div[text() = 'Constrained > Constrained...']",
            null,
            null
    };
    public static String subContextMenuFun[] = {
            "//div[@eventproxy = 'isc_Menu_70']//div[contains(text() , 'Product')]",
            "//div[@eventproxy = 'isc_Menu_70']//table[@width = 146]//div[contains(text() , 'Function')]",
            "//div[@eventproxy = 'isc_Menu_70']//table[@width = 146]//div[contains(text() , 'Location')]",
            "//div[@eventproxy = 'isc_Menu_70']//table[@width = 146]//div[text() = 'Document']",
            "//div[@eventproxy = 'isc_Menu_70']//div[contains(text() , 'Characteristic')]",
            "//div[@eventproxy = 'isc_Menu_70']//div[contains(text() , 'Other')]",
            "//div[@eventproxy = 'isc_Menu_71']//div[contains(text() , 'Add root node...')]",
            "//div[@eventproxy = 'isc_Menu_71']//div[contains(text() , 'Add sub node...')]",
            "//div[@eventproxy = 'isc_Menu_71']//div[contains(text() , 'Edit RDCs...')]",
            "//div[@eventproxy = 'isc_Menu_71']//div[contains(text() , 'Rename RDC...')]",
            "//div[@eventproxy = 'isc_Menu_71']//div[contains(text() , 'Delete node')]",
            "//div[@eventproxy = 'isc_Menu_71']//div[contains(text() , 'Delete aspect with')]",
            "//div[@eventproxy = 'isc_Menu_72']//table[@width = 146]//div[text() = 'Detach']",
            "//div[@eventproxy = 'isc_Menu_72']//div[contains(text() , 'in this Tree')]",
            "//div[@eventproxy = 'isc_Menu_72']//div[contains(text() , 'in all Trees')]",
            "//div[@eventproxy = 'isc_Menu_73']//div[contains(text() , 'Catalogue')]",
            "//div[@eventproxy = 'isc_Menu_73']//div[contains(text() , 'Constrained')]",
            "//div[@eventproxy = 'isc_Menu_73']//div[contains(text() , 'Abstract')]",
            "//div[@eventproxy = 'isc_Menu_80']//div[contains(@style ,'125px')]//div[text() = 'Catalogue']",
            "//div[@eventproxy = 'isc_Menu_80']//div[contains(@style ,'125px')]//div[text() = 'Catalogue > Constrained...']",
            "//div[@eventproxy = 'isc_Menu_80']//div[contains(@style ,'125px')]//div[text() = 'Abstract > Constrained...']",
            "//div[@eventproxy = 'isc_Menu_80']//div[contains(@style ,'125px')]//div[text() = 'Constrained > Abstract...']",
            "//div[@eventproxy = 'isc_Menu_80']//div[contains(@style ,'125px')]//div[text() = 'Constrained > Constrained...']",
            null,
            null
    };
    public static String subContextDocMenuDoc[] = {
            "//div[@eventproxy = 'isc_Menu_41']//div[contains(text() , 'Product')]",
            "//div[@eventproxy = 'isc_Menu_41']//table[@width = 146]//div[contains(text() , 'Function')]",
            "//div[@eventproxy = 'isc_Menu_41']//table[@width = 146]//div[contains(text() , 'Location')]",
            "//div[@eventproxy = 'isc_Menu_41']//table[@width = 146]//div[text() = 'Document']",
            "//div[@eventproxy = 'isc_Menu_41']//div[contains(text() , 'Characteristic')]",
            "//div[@eventproxy = 'isc_Menu_41']//div[contains(text() , 'Other')]",
            "//div[@eventproxy = 'isc_Menu_43']//div[contains(text() , 'Add root node...')]",
            "//div[@eventproxy = 'isc_Menu_43']//div[contains(text() , 'Add sub node...')]",
            "//div[@eventproxy = 'isc_Menu_43']//div[contains(text() , 'Edit RDCs...')]",
            "//div[@eventproxy = 'isc_Menu_43']//div[contains(text() , 'Rename RDC...')]",
            "//div[@eventproxy = 'isc_Menu_43']//div[contains(text() , 'Delete node')]",
            "//div[@eventproxy = 'isc_Menu_43']//div[contains(text() , 'Delete aspect with')]",
            "//div[@eventproxy = 'isc_Menu_46']//table[@width = 146]//div[text() = 'Detach']",
            "//div[@eventproxy = 'isc_Menu_46']//div[contains(text() , 'in this Tree')]",
            "//div[@eventproxy = 'isc_Menu_46']//div[contains(text() , 'in all Trees')]",
            "//div[@eventproxy = 'isc_Menu_47']//div[contains(text() , 'Catalogue Document')]",
            "//div[@eventproxy = 'isc_Menu_47']//div[contains(text() , 'Constrained Document')]",
            "//div[@eventproxy = 'isc_Menu_47']//div[contains(text() , 'Abstract Document')]",
            "//div[@eventproxy = 'isc_Menu_56']//div[contains(@style ,'125px')]//div[contains(text() , 'Document Catalogue')]",
            "//div[@eventproxy = 'isc_Menu_56']//div[contains(@style ,'125px')]//div[text() = 'Catalogue > Constrained...']",
            "//div[@eventproxy = 'isc_Menu_56']//div[contains(@style ,'125px')]//div[text() = 'Abstract > Constrained...']",
            "//div[@eventproxy = 'isc_Menu_56']//div[contains(@style ,'125px')]//div[text() = 'Constrained > Abstract...']",
            "//div[@eventproxy = 'isc_Menu_56']//div[contains(@style ,'125px')]//div[text() = 'Constrained > Constrained...']",
            "//div[@eventproxy = 'isc_Menu_20']//div[text() = 'Create document']",
            "//div[@eventproxy = 'isc_Menu_20']//div[text() = 'Document wizard']"
    };
    public static String contextMenu[][] =  {
        {
                "//div[contains(@eventproxy,'InstanceWindow_0')]//table[@height='18px']//td[contains(text() , 'Edit')]",
                "//div[contains(@eventproxy,'InstanceWindow_0_max')]",
                "//div[contains(@eventproxy,'InstanceWindow_0_min')]",
                "//div[contains(@eventproxy,'InstanceWindow_0_cl')]",
                "//div[contains(@eventproxy,'InstanceWindow_0')]//img[contains(@src,'abstract')]",
                "//div[contains(@eventproxy,'InstanceWindow_0')]//img[contains(@src,'fun')]",
                "//div[contains(@eventproxy,'InstanceWindow_0')]//img[contains(@src,'loc')]",
                "//div[contains(@eventproxy,'InstanceWindow_0')]//img[contains(@src,'char')]",
                "//div[contains(@eventproxy,'InstanceWindow_0')]//img[contains(@src,'other')]",
                "//div[contains(@eventproxy,'InstanceWindow_0')]//div[text() = 'Save']"
        },{
            "//div[contains(@eventproxy,'KBWindow_3')]//table[@height = '18px']//td[text() = 'Linking to']",
            "//div[contains(@eventproxy,'KBWindow_3_max')]",
            "//div[contains(@eventproxy,'KBWindow_3_min')]",
            "//div[contains(@eventproxy,'KBWindow_3_cl')]",
            "//div[contains(@eventproxy,'KBWindow_3')]//div[text() = 'Find ...']",
            "//div[contains(@eventproxy,'KBWindow_3')]//div[text() = 'Save']",
            "//div[contains(@eventproxy,'KBWindow_3')]//div[text() = 'Cancel']",
            null,
            null,
            null
        },{
            "//div[contains(@eventproxy,'HistoryWindow')]//table[@height = '18px']//td[text() = 'History']",
            "//div[contains(@eventproxy,'HistoryWindow_max')]",
            "//div[contains(@eventproxy,'HistoryWindow_min')]",
            "//div[contains(@eventproxy,'HistoryWindow_cl')]",
            null,
            null,
            null,
            null,
            null,
            null
        },{
            "//div[contains(@eventproxy,'InstanceDetailsWindow_0')]//table[@height = '18px']//td[contains(text(), 'Details')]",
            null,
            null,
            "//div[contains(@eventproxy,'InstanceDetailsWindow_0_cl')]",
            "//div[contains(@eventproxy,'InstanceDetailsWindow_0')]//div[text() = 'Close']",
            null,
            null,
            null,
            null,
            null,
            null
        },{
            "//div[contains(@eventproxy,'InstanceLocatorWindow_0')]//table[@height = '18px']//td[contains(text() , 'Locator')]",
            null,
            null,
            "//div[contains(@eventproxy,'InstanceLocatorWindow_0_cl')]",
            "//div[contains(@eventproxy,'InstanceLocatorWindow')]//div[contains(@eventproxy,'ItemForm_1')]//div[text() = 'Find...']",
            "//div[contains(@eventproxy,'InstanceLocatorWindow')]//div[contains(@eventproxy,'ItemForm_2')]//div[text() = 'Find...']",
            "//div[contains(@eventproxy,'InstanceLocatorWindow')]//div[contains(@eventproxy,'ItemForm_3')]//div[text() = 'Find...']",
            null,
            null,
            null
        },{
            "//div[contains(@eventproxy,'PrintProductWindow_0')]//table[@height = '18px']//td[contains(text() , 'Print')]",
            null,
            null,
            "//div[contains(@eventproxy,'PrintProductWindow_0_cl')]",
            "//div[contains(@eventproxy,'PrintProductWindow_0')]//div[text() = 'Print']",
            null,
            null,
            null,
            null,
            null
        }
    };
    public static String documentContextMenu[][] =  {
            {
                    "//div[contains(@eventproxy,'InstanceWindow_0')]//table[@height='18px']//td[contains(text() , 'Edit')]",
                    "//div[contains(@eventproxy,'InstanceWindow_0_max')]",
                    "//div[contains(@eventproxy,'InstanceWindow_0_min')]",
                    "//div[contains(@eventproxy,'InstanceWindow_0_cl')]",
                    "//div[contains(@eventproxy,'InstanceWindow_0')]//img[contains(@src,'abstract')]",
                    "//div[contains(@eventproxy,'InstanceWindow_0')]//img[contains(@src,'fun')]",
                    "//div[contains(@eventproxy,'InstanceWindow_0')]//img[contains(@src,'loc')]",
                    "//div[contains(@eventproxy,'InstanceWindow_0')]//img[contains(@src,'char')]",
                    "//div[contains(@eventproxy,'InstanceWindow_0')]//img[contains(@src,'other')]",
                    "//div[contains(@eventproxy,'InstanceWindow_0')]//div[text() = 'Save']"
            },{
            "//div[contains(@eventproxy,'SetPlantWindow_0')]//table[@height = '18px']//td[contains(text() = 'Set Plant')]",
            null,
            null,
            "//div[contains(@eventproxy,'SetPlantWindow_0_cl')]",
            "//div[contains(@eventproxy,'KBWindow_0')]//div[text() = 'Set Plant']",
            null,
            null,
            null,
            null,
            null
    },{
            "//div[contains(@eventproxy,'HistoryWindow')]//table[@height = '18px']//td[text() = 'History']",
            "//div[contains(@eventproxy,'HistoryWindow_max')]",
            "//div[contains(@eventproxy,'HistoryWindow_min')]",
            "//div[contains(@eventproxy,'HistoryWindow_cl')]",
            null,
            null,
            null,
            null,
            null,
            null
    },{
            "//div[contains(@eventproxy,'InstanceDetailsWindow_0')]//table[@height = '18px']//td[contains(text(), 'Details')]",
            null,
            null,
            "//div[contains(@eventproxy,'InstanceDetailsWindow_0_cl')]",
            "//div[contains(@eventproxy,'InstanceDetailsWindow_0')]//div[text() = 'Close']",
            null,
            null,
            null,
            null,
            null,
            null
    },{
            "//div[contains(@eventproxy,'DocumentLocatorWindow_0')]//table[@height = '18px']//td[contains(text() , 'Locator')]",
            null,
            null,
            "//div[contains(@eventproxy,'DocumentLocatorWindow_0_cl')]",
            "//div[contains(@eventproxy,'DocumentLocatorWindow')]//div[contains(@eventproxy,'ItemForm_0')]//div[text() = 'Find...']",
            null,
            null,
            null,
            null,
            null
    },{
            "//div[contains(@eventproxy,'PrintProductWindow_0')]//table[@height = '18px']//td[contains(text() , 'Print')]",
            null,
            null,
            "//div[contains(@eventproxy,'PrintProductWindow_0_cl')]",
            "//div[contains(@eventproxy,'PrintProductWindow_0')]//div[text() = 'Print']",
            null,
            null,
            null,
            null,
            null
    }
    };
    public static String subDocContextMenu[][] = {
            {
                    "//div[contains(@eventproxy, 'NounModifier')]//table[@height = '18px']//td[contains(text(),'Modifier List')]",
                     null,
                     null,
                    "//div[contains(@eventproxy, 'NounModifierPickerWindow_0_cl')]",
                    "//div[contains(@eventproxy, 'NounModifierPickerWindow_0')]//div[text() = 'Save']",
                    "//div[contains(@eventproxy, 'NounModifierPickerWindow_0')]//div[text() = 'Clear']",
                    null,
                    null,
                    null,
                    null
            },{
                    "//div[contains(@eventproxy, 'dataManagerWindow_0')]//table[@height = '18px']//td[contains(text() , 'Metadata')]",
                    "//div[contains(@eventproxy, 'dataManagerWindow_0_max')]",
                    "//div[contains(@eventproxy, 'dataManagerWindow_0_min')]",
                    "//div[contains(@eventproxy, 'dataManagerWindow_0_cl')]",
                    "//div[contains(@eventproxy, 'dataManagerWindow_0')]//div[text() = 'Search...']",
                    "//div[contains(@eventproxy, 'dataManagerWindow_0')]//div[text() = 'To be updated...']",
                    null,
                    null,
                    null,
                    null
            },{
                    "//div[contains(@eventproxy, 'KBWindow_0')]//table[@height='18px']//td[contains(text(),'catalogue')]",
                    "//div[contains(@eventproxy, 'KBWindow_0_max')]",
                    "//div[contains(@eventproxy, 'KBWindow_0_min')]",
                    "//div[contains(@eventproxy, 'KBWindow_0_cl')]",
                    "//div[contains(@eventproxy, 'KBWindow_0')]//div[text()='Search']",
                    "//div[contains(@eventproxy, 'KBWindow_0')]//div[text()='Reset']",
                    "//div[contains(@eventproxy, 'KBWindow_0')]//div[text()='Report']",
                    null,
                    null,
                    null
            },{
                    "//div[contains(@eventproxy, 'KBWindow_1')]//table[@height='18px']//td[contains(text(),'Metadata Search')]",
                    "//div[contains(@eventproxy, 'KBWindow_1_max')]",
                    "//div[contains(@eventproxy, 'KBWindow_1_min')]",
                    "//div[contains(@eventproxy, 'KBWindow_1_cl')]",
                    "//div[contains(@eventproxy, 'KBWindow_1')]//div[text()='Search']",
                    null,
                    null,
                    null,
                    null,
                    null
            },{
                   "//div[contains(@eventproxy, 'orderWizardFirstWindow')]//table[@height='18px']//td[contains(text(),'Order Wizard')]",
                   null,
                   null,
                   "//div[contains(@eventproxy, 'orderWizardFirstWindow') and contains(@eventproxy, '_cl')]",
                   "//div[contains(@eventproxy, 'orderWizardFirstWindow')]//div[contains(text(),'Next')]",
                   null,
                   null,
                   null,
                   null,
                   null
            },{
                 "//div[contains(@eventproxy, 'KBWindow_2')]//table[@height='18px']//td[contains(text(),'to change')]",
                 "//div[contains(@eventproxy, 'KBWindow_2_max')]",
                 "//div[contains(@eventproxy, 'KBWindow_2_min')]",
                 "//div[contains(@eventproxy, 'KBWindow_2_cl')]",
                 "//div[contains(@eventproxy, 'KBWindow_2')]//div[text()='Search']",
                 "//div[contains(@eventproxy, 'KBWindow_2')]//div[text()='Reset']",
                 "//div[contains(@eventproxy, 'KBWindow_2')]//div[text()='Report']",
                 null,
                 null,
                 null
            },{
                 "//div[contains(@eventproxy, 'KBWindow_1')]//table[@height='18px']//td[contains(text(),'Metadata Search')]",
                 "//div[contains(@eventproxy, 'KBWindow_1_max')]",
                 "//div[contains(@eventproxy, 'KBWindow_1_min')]",
                 "//div[contains(@eventproxy, 'KBWindow_1_cl')]",
                 "//div[contains(@eventproxy, 'KBWindow_1')]//div[text()='Search']",
                 null,
                 null,
                 null,
                 null,
                 null
            }
    };
    public static String subFunContextMenu[][] = {
            {
                    "//div[contains(@eventproxy, 'NounModifier')]//table[@height = '18px']//td[contains(text(),'Modifier List')]",
                    null,
                    null,
                    "//div[contains(@eventproxy, 'NounModifierPickerWindow_0_cl')]",
                    "//div[contains(@eventproxy, 'NounModifierPickerWindow_0')]//div[text() = 'Save']",
                    "//div[contains(@eventproxy, 'NounModifierPickerWindow_0')]//div[text() = 'Clear']",
                    null,
                    null,
                    null,
                    null
            },{
            "//div[contains(@eventproxy, 'dataManagerWindow_0')]//table[@height = '18px']//td[contains(text() , 'Metadata')]",
            "//div[contains(@eventproxy, 'dataManagerWindow_0_max')]",
            "//div[contains(@eventproxy, 'dataManagerWindow_0_min')]",
            "//div[contains(@eventproxy, 'dataManagerWindow_0_cl')]",
            "//div[contains(@eventproxy, 'dataManagerWindow_0')]//div[text() = 'Search...']",
            "//div[contains(@eventproxy, 'dataManagerWindow_0')]//div[text() = 'To be updated...']",
            null,
            null,
            null,
            null
    },{
            "//div[contains(@eventproxy, 'KBWindow_4')]//table[@height='18px']//td[contains(text(),'catalogue')]",
            "//div[contains(@eventproxy, 'KBWindow_4_max')]",
            "//div[contains(@eventproxy, 'KBWindow_4_min')]",
            "//div[contains(@eventproxy, 'KBWindow_4_cl')]",
            "//div[contains(@eventproxy, 'KBWindow_4')]//div[text()='Search']",
            "//div[contains(@eventproxy, 'KBWindow_4')]//div[text()='Reset']",
            "//div[contains(@eventproxy, 'KBWindow_4')]//div[text()='Report']",
            null,
            null,
            null
    },{
            "//div[contains(@eventproxy, 'KBWindow_1')]//table[@height='18px']//td[contains(text(),'Metadata Search')]",
            "//div[contains(@eventproxy, 'KBWindow_1_max')]",
            "//div[contains(@eventproxy, 'KBWindow_1_min')]",
            "//div[contains(@eventproxy, 'KBWindow_1_cl')]",
            "//div[contains(@eventproxy, 'KBWindow_1')]//div[text()='Search']",
            null,
            null,
            null,
            null,
            null
    },{
            "//body/div[contains(@eventproxy, 'orderWizardFirstWindow')][last()-1]//table[@height='18px']//td[contains(text(),'Order Wizard')]",
            null,
            null,
            "//body/div[contains(@eventproxy, 'orderWizardFirstWindow')][last()-1]//div[contains(@eventproxy,'close')]",
            "//body/div[contains(@eventproxy, 'orderWizardFirstWindow')][last()-1]]//div[contains(text(),'Next')]",
            null,
            null,
            null,
            null,
            null
    },{
            "//div[contains(@eventproxy, 'KBWindow_5')]//table[@height='18px']//td[contains(text(),'to change')]",
            "//div[contains(@eventproxy, 'KBWindow_5_max')]",
            "//div[contains(@eventproxy, 'KBWindow_5_min')]",
            "//div[contains(@eventproxy, 'KBWindow_5_cl')]",
            "//div[contains(@eventproxy, 'KBWindow_5')]//div[text()='Search']",
            "//div[contains(@eventproxy, 'KBWindow_5')]//div[text()='Reset']",
            "//div[contains(@eventproxy, 'KBWindow_5')]//div[text()='Report']",
            null,
            null,
            null
    },{
            "//div[contains(@eventproxy, 'KBWindow_1')]//table[@height='18px']//td[contains(text(),'Metadata Search')]",
            "//div[contains(@eventproxy, 'KBWindow_1_max')]",
            "//div[contains(@eventproxy, 'KBWindow_1_min')]",
            "//div[contains(@eventproxy, 'KBWindow_1_cl')]",
            "//div[contains(@eventproxy, 'KBWindow_1')]//div[text()='Search']",
            null,
            null,
            null,
            null,
            null
    }
    };
    public static String subDocumentContextMenu[][] = {
            {
                    "//div[contains(@eventproxy, 'NounModifier')]//table[@height = '18px']//td[contains(text(),'Modifier List')]",
                    null,
                    null,
                    "//div[contains(@eventproxy, 'NounModifierPickerWindow_0_cl')]",
                    "//div[contains(@eventproxy, 'NounModifierPickerWindow_0')]//div[text() = 'Save']",
                    "//div[contains(@eventproxy, 'NounModifierPickerWindow_0')]//div[text() = 'Clear']",
                    null,
                    null,
                    null,
                    null
            },{
            "//div[contains(@eventproxy, 'dataManagerWindow_0')]//table[@height = '18px']//td[contains(text() , 'Metadata')]",
            "//div[contains(@eventproxy, 'dataManagerWindow_0_max')]",
            "//div[contains(@eventproxy, 'dataManagerWindow_0_min')]",
            "//div[contains(@eventproxy, 'dataManagerWindow_0_cl')]",
            "//div[contains(@eventproxy, 'dataManagerWindow_0')]//div[text() = 'Search...']",
            "//div[contains(@eventproxy, 'dataManagerWindow_0')]//div[text() = 'To be updated...']",
            null,
            null,
            null,
            null
    },{
            "//div[contains(@eventproxy, 'KBWindow_6')]//table[@height='18px']//td[contains(text(),'catalogue')]",
            "//div[contains(@eventproxy, 'KBWindow_6_max')]",
            "//div[contains(@eventproxy, 'KBWindow_6_min')]",
            "//div[contains(@eventproxy, 'KBWindow_6_cl')]",
            "//div[contains(@eventproxy, 'KBWindow_6')]//div[text()='Search']",
            "//div[contains(@eventproxy, 'KBWindow_6')]//div[text()='Reset']",
            "//div[contains(@eventproxy, 'KBWindow_6')]//div[text()='Report']",
            null,
            null,
            null
    },{
            "//div[contains(@eventproxy, 'KBWindow_1')]//table[@height='18px']//td[contains(text(),'Metadata Search')]",
            "//div[contains(@eventproxy, 'KBWindow_1_max')]",
            "//div[contains(@eventproxy, 'KBWindow_1_min')]",
            "//div[contains(@eventproxy, 'KBWindow_1_cl')]",
            "//div[contains(@eventproxy, 'KBWindow_1')]//div[text()='Search']",
            null,
            null,
            null,
            null,
            null
    },{
            "//body/div[contains(@eventproxy, 'orderWizardFirstWindow')][last()-1]//table[@height='18px']//td[contains(text(),'Order Wizard')]",
            null,
            null,
            "//body/div[contains(@eventproxy, 'orderWizardFirstWindow')][last()-1]//div[contains(@eventproxy,'close')]",
            "//body/div[contains(@eventproxy, 'orderWizardFirstWindow')][last()-1]]//div[contains(text(),'Next')]",
            null,
            null,
            null,
            null,
            null
    },{
            "//div[contains(@eventproxy, 'KBWindow_7')]//table[@height='18px']//td[contains(text(),'to change')]",
            "//div[contains(@eventproxy, 'KBWindow_7_max')]",
            "//div[contains(@eventproxy, 'KBWindow_7_min')]",
            "//div[contains(@eventproxy, 'KBWindow_7_cl')]",
            "//div[contains(@eventproxy, 'KBWindow_7')]//div[text()='Search']",
            "//div[contains(@eventproxy, 'KBWindow_7')]//div[text()='Reset']",
            "//div[contains(@eventproxy, 'KBWindow_7')]//div[text()='Report']",
            null,
            null,
            null
    },{
            "//div[contains(@eventproxy, 'KBWindow_1')]//table[@height='18px']//td[contains(text(),'Metadata Search')]",
            "//div[contains(@eventproxy, 'KBWindow_1_max')]",
            "//div[contains(@eventproxy, 'KBWindow_1_min')]",
            "//div[contains(@eventproxy, 'KBWindow_1_cl')]",
            "//div[contains(@eventproxy, 'KBWindow_1')]//div[text()='Search']",
            null,
            null,
            null,
            null,
            null
    }
    };
}

