package me.check.context;

public interface Builder {
    public Builder setSynchronize(String synchronize);
    public Builder setEdit(String edit);
    public Builder setEditMaster(String editMaster);
    public Builder setAddContact(String addContact);
    public Builder setMappingLink(String mappingLink);
    public Builder setModelTree(String modelTree);
    public Builder setDetach(String detach);
    public Builder setMoveItem(String moveItem);
    public Builder setReplaceMeta(String replaceMeta);
    public Builder setVisibility(String visibility);
    public Builder setHistory(String history);
    public Builder setDetails(String details);
    public Builder setLocator(String locator);
    public Builder setOrderItem(String orderItem);
    public Builder setChangeItem(String changeItem);
    public Builder setPrint(String print);
    public Builder setRefresh(String refresh);
    public Builder setExpand(String expand);
    public Builder setCollapse(String collapse);
    public Builder setNm(String nm);
    public Builder setProduct(String product);
    public Builder setFunction(String function);
    public Builder setLocation(String location);
    public Builder setDocument(String document);
    public Builder setCharacteristic(String characteristic);
    public Builder setOther(String other);
    public Builder setRoot(String root);
    public Builder setSub(String sub);
    public Builder setEditRdc(String editRdc);
    public Builder setRenameRdc(String renameRdc);
    public Builder setDeleteNode(String deleteNode);
    public Builder setDeleteAspect(String deleteAspect);
    public Builder setOrderCatalogue(String orderCatalogue);
    public Builder setOrderConstraint(String orderConstraint);
    public Builder setOrderAbstract(String orderAbstract);
}
