package resources;

public class Links {
    public static String[][] searchLinks = {{"//div[text() = 'Equipment']","//table[@height = '18px']//td[text() = 'Equipment Manager']",
            "//div[contains(@eventproxy,'QueryManagerWindowNew_0_max')]",
            "//div[contains(@eventproxy,'QueryManagerWindowNew_0_min')]",
            "//div[contains(@eventproxy,'QueryManagerWindowNew_0_cl')]",
            "//div[contains(@eventproxy,'QueryManagerWindowNew_0')]//input[@name = 'searchTextBox']",
            "//div[contains(@eventproxy,'QueryManagerWindowNew_0')]//div[text() = 'Start Editing']",
            "//div[contains(@eventproxy,'QueryManagerWindowNew_0')]//div[text() = 'Conditions reset']",
            "//div[contains(@eventproxy,'QueryManagerWindowNew_0')]//div[text() = 'Layout reset']",
            "//div[contains(@eventproxy,'QueryManagerWindowNew_0')]//div[text() = 'Report...']",
            "//div[contains(@eventproxy,'QueryManagerWindowNew_0')]//div[text() = 'Search']",
            "//div[contains(@eventproxy,'QueryManagerWindowNew_0')]//td[contains(text(),'Found')]"
         },{"//div[text() = 'Contact']","//table[@height='18px']//td[text()='Contact Manager']",
            "//div[contains(@eventproxy,'ContactManagerWindow_0_max')]",
            "//div[contains(@eventproxy,'ContactManagerWindow_0_min')]",
            "//div[contains(@eventproxy,'ContactManagerWindow_0_cl')]",
            "//div[contains(@eventproxy,'ContactManagerWindow_0')]//input[@name = 'CMSearchText']",
            null,
            null,
            null,
            null,
            "//div[contains(@eventproxy,'CMDynamic')]//div[text()='Search']",
            "//td[contains(text(),'record')]"
    },{
            "//div[text() = 'Document']",
            "//table[@height = '18px']//td[text() = 'Document Manager']",
            "//div[contains(@eventproxy,'DocumentManagerSearchWindowNew_0_max')]",
            "//div[contains(@eventproxy,'DocumentManagerSearchWindowNew_0_min')]",
            "//div[contains(@eventproxy,'DocumentManagerSearchWindowNew_0_cl')]",
            "//div[contains(@eventproxy,'DocumentManagerSearchWindowNew_0')]//input[@name = 'searchTextBox']",
            "//div[contains(@eventproxy,'DocumentManagerSearchWindowNew_0')]//div[text() = 'Start Editing']",
            "//div[contains(@eventproxy,'DocumentManagerSearchWindowNew_0')]//div[text() = 'Conditions reset']",
            "//div[contains(@eventproxy,'DocumentManagerSearchWindowNew_0')]//div[text() = 'Layout reset']",
            "//div[contains(@eventproxy,'DocumentManagerSearchWindowNew_0')]//div[text() = 'Report...']",
            "//div[contains(@eventproxy,'DocumentManagerSearchWindowNew_0')]//div[text() = 'Search']",
            "//div[contains(@eventproxy,'DocumentManagerSearchWindowNew_0')]//td[contains(text(),'Found')]"
    },{
            "//div[text() = 'Aspect']",
            "//table[@height = '18px']//td[text() = 'Aspect Manager']",
            "//div[contains(@eventproxy,'RecordSearchWindow_0_max')]",
            "//div[contains(@eventproxy,'RecordSearchWindow_0_min')]",
            "//div[contains(@eventproxy,'RecordSearchWindow_0_cl')]",
            "//div[contains(@eventproxy,'RecordSearchWindow_0')]//input[@name = 'searchTextBox']",
            "//div[contains(@eventproxy,'RecordSearchWindow_0')]//div[text() = 'Start Editing']",
            "//div[contains(@eventproxy,'RecordSearchWindow_0')]//div[text() = 'Conditions reset']",
            "//div[contains(@eventproxy,'RecordSearchWindow_0')]//div[text() = 'Layout reset']",
            "//div[contains(@eventproxy,'RecordSearchWindow_0')]//div[text() = 'Report...']",
            "//div[contains(@eventproxy,'RecordSearchWindow_0')]//div[text() = 'Search']",
            "//div[contains(@eventproxy,'RecordSe')]//td[contains(text(),'Found')]"
    },{
            "//div[text() = 'Comment']",
            "//table[@height = '18px']//td[text() = 'Comments']",
            "//div[contains(@eventproxy,'CommentSearchWindowNew_0_max')]",
            "//div[contains(@eventproxy,'CommentSearchWindowNew_0_min')]",
            "//div[contains(@eventproxy,'CommentSearchWindowNew_0_cl')]",
            "//div[contains(@eventproxy,'CommentSearchWindowNew_0')]//input[@name = 'searchText']",
            null,
            null,
            "//div[contains(@eventproxy,'CommentSearchWindowNew_0')]//div[text() = 'Reset']",
            "//div[contains(@eventproxy,'CommentSearchWindowNew_0')]//div[text() = 'Report']",
            "//div[contains(@eventproxy,'CommentSearchWindowNew_0')]//div[text() = 'Search']",
            "//td[contains(text(),'row')]"
    },{

    }
    };

    public static String[][] toolLinks = {{
            "//div[text() = 'Trashed Items Manager']",
            null,
            "//table[@height = '18px']//td[text() = 'Trashed Items Manager']",
            "//div[contains(@eventproxy,'TrashedItemsManagerWindow_0_max')]",
            "//div[contains(@eventproxy,'TrashedItemsManagerWindow_0_min')]",
            "//div[contains(@eventproxy,'TrashedItemsManagerWindow_0_cl')]",
            "//div[contains(@eventproxy,'TrashedItemsManagerWindow_0')]//input[@name = 'searchTextBox']",
            "//div[contains(@eventproxy,'TrashedItemsManagerWindow_0')]//div[text() = 'Conditions reset']",
            "//div[contains(@eventproxy,'TrashedItemsManagerWindow_0')]//div[text() = 'Layout reset']",
            "//div[contains(@eventproxy,'TrashedItemsManagerWindow_0')]//div[text() = 'Search']",
            "//div[contains(@eventproxy,'TrashedItemsManagerWindow_0')]//td[contains(text(),'Found')]"
    },{
            "//div[text() = 'Queue Manager']",
            null,
            "//table[@height = '18px']//td[text() = 'Queue manager']",
            "//div[contains(@eventproxy,'QueueManagerWindow_0_max')]",
            "//div[contains(@eventproxy,'QueueManagerWindow_0_min')]",
            "//div[contains(@eventproxy,'QueueManagerWindow_0_cl')]",
            "//div[contains(@eventproxy,'QueueManagerWindow_0')]//table[contains(@style,'772') ]",
            null,
            null,
            "//div[contains(@eventproxy,'QueueManagerWindow_0')]//table[contains(@style,'772') ]",
            "//div[contains(@eventproxy,'ListMenu')]//div[text() = 'EXPORT']",
            "//div[contains(@eventproxy,'QueueManagerWindowList')]//table[@width = 856]//tbody",
            "tr",
    },{
            "//div[text() = 'Import Meta']",
            null,
            "//table[@height = '18px']//td[text() = 'Import Meta Manager']",
            "//div[contains(@eventproxy,'ImportMetaWindow_0_max')]",
            "//div[contains(@eventproxy,'ImportMetaWindow_0_min')]",
            "//div[contains(@eventproxy,'ImportMetaWindow_0_cl')]",
            null,
            "//div[contains(@eventproxy,'ImportMetaWindow_0')]//div[text() = 'Add file']",
            "//div[contains(@eventproxy,'ImportMetaWindow_0')]//div[text() = 'Import']",
            "not needed"
    },{
            "//div[text() = 'Import (dynamic)']",
            null,
            "//table[@height = '18px']//td[text() = 'Import Manager']",
            "//div[contains(@eventproxy,'SyncManagerWindow_0_max')]",
            "//div[contains(@eventproxy,'SyncManagerWindow_0_min')]",
            "//div[contains(@eventproxy,'SyncManagerWindow_0_cl')]",
            null,
            "//div[contains(@eventproxy,'SyncManagerWindow_0')]//div[text() = 'Prepare']",
            "//div[contains(@eventproxy,'SyncManagerWindow_0')]//div[text() = 'Import']",
            "not needed"
    },{
            "//div[text() = 'Administration']",
            "//div[@role = 'menu']//div[text() = 'Plant']",

            "//table[@height = '18px']//td[text() = 'Plant Search']",
            "//div[contains(@eventproxy,'PlantManagerSearchWindow_0_max')]",
            "//div[contains(@eventproxy,'PlantManagerSearchWindow_0_min')]",
            "//div[contains(@eventproxy,'PlantManagerSearchWindow_0_cl')]",
            "//div[contains(@eventproxy,'PlantManagerSearchWindow_0')]//input",
            "//div[contains(@eventproxy,'PlantManagerSearchWindow_0')]//div[text() ='Search']",
            null,
            "//div[contains(@eventproxy,'PlantManagerSearchWindow_0')]//div[text() ='Search']",
            "//table[@width = '596']//tbody",
            "tr",

    },{
            "//div[text() = 'Administration']",
            "//div[@role = 'menu']//div[text() = 'User Profile']",

            "//table[@height = '18px']//td[text() = 'User Profile']",
            null,
            null,
            "//div[contains(@eventproxy,'UserProfileWindow_0_cl')]",
            "//div[contains(@eventproxy,'UserProfileWindow_0')]//input[@name = 'password']",
            "//div[contains(@eventproxy,'UserProfileWindow_0')]//div[text() = 'Save']",
            null,
            "not needed"

    }};
    public static String[][] dataManagerLinks = {{
            "//div[text() = 'Link Types Manager']",
            null,
            null,
            "//table[@height = '18px']//td[text() = 'Link Types Manager']",

            "//div[contains(@eventproxy,'LinkTypesManager_0_max')]",
            "//div[contains(@eventproxy,'LinkTypesManager_0_min')]",
            "//div[contains(@eventproxy,'LinkTypesManager_0_cl')]",
            null,
            "//div[contains(@eventproxy,'LinkTypesManager_0')]//div[text() = 'Add']",
            "//div[contains(@eventproxy,'LinkTypesManager_0')]//div[text() = 'Edit']",
            "//div[contains(@eventproxy,'LinkTypesManager_0')]//div[text() = 'Remove']",
            "//table[@width = '356']//tbody",
            "tr",
    },{
            "//div[text() = 'Reports Manager']",
            null,
            null,
            "//table[@height = '18px']//td[text() = 'Report Manager']",

            "//div[contains(@eventproxy,'ReportManagerWindow_0_max')]",
            "//div[contains(@eventproxy,'ReportManagerWindow_0_min')]",
            "//div[contains(@eventproxy,'ReportManagerWindow_0_cl')]",
            "//div[contains(@eventproxy,'ReportManagerWindow_0')]//div[contains(@style , 'width:746')]",
            "//div[contains(@eventproxy,'ReportManagerWindow_0')]//div[text() = 'Generate']",
            null,
            null,
            "Not needed"
    },{
            "//div[text() = 'Unit Manager']",
            null,
            null,
            "//table[@height = '18px']//td[text() = 'Unit Manager']",
            "//div[contains(@eventproxy,'UnitManagerWindow_0_max')]",
            "//div[contains(@eventproxy,'UnitManagerWindow_0_min')]",
            "//div[contains(@eventproxy,'UnitManagerWindow_0_cl')]",
            "//div[contains(@eventproxy,'UnitManagerWindow_0')]//input[@name = 'searchText']",
            "//div[contains(@eventproxy,'UnitManagerWindow_0')]//div[text() = 'Search']",
            null,
            null,
            "//div[contains(@eventproxy,'UnitManagerWindow_0')]//div[text() = 'Search']",
            "//table[@width = '580']//tbody",
            "tr",
    },{
            "//div[text() = 'Role Manager']",
            null,
            null,
            "//table[@height = '18px']//td[text() = 'Role Manager']",
            "//div[contains(@eventproxy,'RoleManagerWindow_0_max')]",
            "//div[contains(@eventproxy,'RoleManagerWindow_0_min')]",
            "//div[contains(@eventproxy,'RoleManagerWindow_0_cl')]",
            null,
            "//div[contains(@eventproxy,'RoleManagerWindow_0')]//div[text() = 'Add Role']",
            "//div[contains(@eventproxy,'RoleManagerWindow_0')]//div[text() = 'Start Editing']",
            "//div[contains(@eventproxy,'RoleManagerWindow_0')]//div[text() = 'Remove Role']",
            "Not needed"
    },{
            "//div[text() = 'Masterdata']",
            "//div[contains(@eventproxy,'isc_Menu')]//div[text() ='Equipment']",
            null,
            "//table[@height = '18px']//td[text() = 'Masterdata -> Equipment']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_0_max')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_0_min')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_0_cl')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_0')]//input[@name = 'searchText']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_0')]//div[text() = 'Reset']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_0')]//div[text() = 'Report']",
            null,
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_0')]//div[text() = 'Search']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_0')]//td[contains(text(),'Found')]",

    },{
            "//div[text() = 'Masterdata']",
            "//div[contains(@eventproxy,'isc_Menu')]//div[text() ='Spare Parts']",
            null,
            "//table[@height = '18px']//td[text() = 'Masterdata -> Spare Parts']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_1_max')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_1_min')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_1_cl')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_1')]//input[@name = 'searchText']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_1')]//div[text() = 'Reset']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_1')]//div[text() = 'Report']",
            null,
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_1')]//div[text() = 'Search']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_1')]//td[contains(text(),'Found')]"
    },{
            "//div[text() = 'Masterdata']",
            "//div[contains(@eventproxy,'isc_Menu')]//div[text() ='Document']",
            null,
            "//table[@height = '18px']//td[text() = 'Masterdata -> Documents']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_2_max')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_2_min')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_2_cl')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_2')]//input[@name = 'searchText']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_2')]//div[text() = 'Reset']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_2')]//div[text() = 'Report']",
            null,
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_2')]//div[text() = 'Search']",
            "//div[contains(@eventproxy,'MasterdataManagerWindowNew_2')]//td[contains(text(),'Found')]",

    },{
            "//div[text() = 'Masterdata']",
            "//div[contains(@eventproxy,'isc_Menu')]//div[text() ='Other...']",
            null,
            "//table[@height = '18px']//td[text() = 'Masterdata -> Other...']",
            "//div[contains(@eventproxy,'MasterdataManagerWindow_0_max')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindow_0_min')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindow_0_cl')]",
            "//div[contains(@eventproxy,'MasterdataManagerWindow_0')]//input[@name = 'searchText']",
            "//div[contains(@eventproxy,'MasterdataManagerWindow_0')]//div[text() = 'Reset']",
            "//div[contains(@eventproxy,'MasterdataManagerWindow_0')]//div[text() = 'Report']",
            null,
            "//div[contains(@eventproxy,'MasterdataManagerWindow_0')]//div[text() = 'Search']",
            "//div[contains(@eventproxy,'MasterdataManagerWindow_0')]//td[contains(text(),'Found')]"
    },{
            "//div[text() = 'N&M Manager']",
            "//div[text() = 'Product']",
            null,
            "//table[@height = '18px']//td[contains(text(),'PRODUCT')]",
            null,
            "//div[contains(@eventproxy,'KBWindow_0_min')]",
            "//div[contains(@eventproxy,'KBWindow_0_cl')]",
            null,
            "//div[contains(@eventproxy,'KBWindow_0')]//div[contains(@style , 'left: 220px')]",
            "//div[contains(@eventproxy,'KBWindow_0')]//div[contains(@style , 'left: 225px')]", //add button
            null,
            "Not needed"
    },{
            "//div[text() = 'N&M Manager']",
            "//div[text() = 'Characteristic']",
            null,
            "//table[@height = '18px']//td[contains(text(),'CHARACTERISTIC')]",
            null,
            "//div[contains(@eventproxy,'KBWindow_1_min')]",
            "//div[contains(@eventproxy,'KBWindow_1_cl')]",
            null,
            "//div[contains(@eventproxy,'KBWindow_1')]//div[contains(@style , 'left: 220px')]",
            "//div[contains(@eventproxy,'KBWindow_1')]//div[contains(@style , 'left: 225px')]", //add button
            null,

            "Not needed"
    },{
            "//div[text() = 'Synchronize']",
            "//div[text()='Master']",
            null,
            "//table[@height = '18px']//td[text() = 'Master Product Synchronization']",
            "//div[contains(@eventproxy,'KBWindow_2_max')]",
            "//div[contains(@eventproxy,'KBWindow_2_min')]",
            "//div[contains(@eventproxy,'KBWindow_2_cl')]",
            "//div[contains(@eventproxy,'KBWindow_2')]//input[@name = 'searchText']",
            "//div[contains(@eventproxy,'KBWindow_2')]//div[text() = 'Reset']",
            "//div[contains(@eventproxy,'KBWindow_2')]//div[text() = 'Report']",
            "//div[contains(@eventproxy,'KBWindow_2')]//div[text() = 'Synchronize']",
            "//div[contains(@eventproxy,'KBWindow_2')]//div[text() = 'Search']",
            "//div[contains(@eventproxy,'KBWindow_2')]//td[contains(text(),'Found')]"
    },{
            "//div[text() = 'Synchronize']",
            "//div[contains(@style , 'top: 42')]//div[text()='Spare Parts']",
            null,
            "//table[@height = '18px']//td[text() = 'Spare Parts Synchronization']",
            "//div[contains(@eventproxy,'KBWindow_3_max')]",
            "//div[contains(@eventproxy,'KBWindow_3_min')]",
            "//div[contains(@eventproxy,'KBWindow_3_cl')]",
            "//div[contains(@eventproxy,'KBWindow_3')]//input[@name = 'searchText']",
            "//div[contains(@eventproxy,'KBWindow_3')]//div[text() = 'Reset']",
            "//div[contains(@eventproxy,'KBWindow_3')]//div[text() = 'Report']",
            "//div[contains(@eventproxy,'KBWindow_3')]//div[text() = 'Synchronize']",
            "//div[contains(@eventproxy,'KBWindow_3')]//div[text() = 'Search']",
            "//div[contains(@eventproxy,'KBWindow_3')]//td[contains(text(),'Found')]"
    },{
            "//div[text() = 'Synchronize']",
            "//div[text()='Instance']",
            "//div[contains(@style , 'top: 52')]//div[text()='Equipment']",
            "//table[@height = '18px']//td[text() = 'Equipment Synchronization']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_0_max')]",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_0_min')]",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_0_cl')]",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_0')]//input[@name = 'searchTextBox']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_0')]//div[text() = 'Conditions reset']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_0')]//div[text() = 'Report...']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_0')]//div[text() = 'Synchronize']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_0')]//div[text() = 'Search']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_0')]//td[contains(text(),'Found')]",
    },{
            "//div[text() = 'Synchronize']",
            "//div[text()='Instance']",
            "//div[contains(@style , 'top: 52')]//div[text()='Documents']",
            "//table[@height = '18px']//td[text() = 'Document Instance Synchronization']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_1_max')]",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_1_min')]",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_1_cl')]",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_1')]//input[@name = 'searchTextBox']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_1')]//div[text() = 'Conditions reset']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_1')]//div[text() = 'Report...']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_1')]//div[text() = 'Synchronize']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_1')]//div[text() = 'Search']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_1')]//td[contains(text(),'Found')]"
    },{
            "//div[text() = 'Synchronize']",
            "//div[text()='Instance']",
            "//div[contains(@style , 'top: 52')]//div[text()='Aspect']",
            "//table[@height = '18px']//td[text() = 'Aspect Synchronization']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_2_max')]",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_2_min')]",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_2_cl')]",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_2')]//input[@name = 'searchTextBox']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_2')]//div[text() = 'Conditions reset']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_2')]//div[text() = 'Report...']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_2')]//div[text() = 'Synchronize']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_2')]//div[text() = 'Search']",
            "//div[contains(@eventproxy,'InstanceSynchronizationWindow_2')]//td[contains(text(),'Found')]"
    }};
}
